// Generated by gencpp from file nlink_parser/LinktrackNodeframe3.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME3_H
#define NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlink_parser/LinktrackNode2.h>

namespace nlink_parser
{
template <class ContainerAllocator>
struct LinktrackNodeframe3_
{
  typedef LinktrackNodeframe3_<ContainerAllocator> Type;

  LinktrackNodeframe3_()
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , nodes()  {
    }
  LinktrackNodeframe3_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , nodes(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _local_time_type;
  _local_time_type local_time;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef std::vector< ::nlink_parser::LinktrackNode2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nlink_parser::LinktrackNode2_<ContainerAllocator> >::other >  _nodes_type;
  _nodes_type nodes;




  typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNodeframe3_

typedef ::nlink_parser::LinktrackNodeframe3_<std::allocator<void> > LinktrackNodeframe3;

typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe3 > LinktrackNodeframe3Ptr;
typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe3 const> LinktrackNodeframe3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nlink_parser

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nlink_parser': ['/home/kinetic/xrobot_ws/src/nlink_parser/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5fe6bc25d71efe36dc5d4595d69025e";
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5fe6bc25d71efe3ULL;
  static const uint64_t static_value2 = 0x6dc5d4595d69025eULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/LinktrackNodeframe3";
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n\
uint8 id\n\
uint32 local_time\n\
uint32 system_time\n\
float32 voltage\n\
LinktrackNode2[] nodes\n\
\n\
================================================================================\n\
MSG: nlink_parser/LinktrackNode2\n\
uint8 role\n\
uint8 id\n\
float32 dis\n\
float32 fp_rssi\n\
float32 rx_rssi\n\
";
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.local_time);
      stream.next(m.system_time);
      stream.next(m.voltage);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNodeframe3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::LinktrackNodeframe3_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "local_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.local_time);
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlink_parser::LinktrackNode2_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME3_H
